name = "nonblog"
license = "MIT"
licenselink = "https://github.com/heavywatal/hugo-theme-nonblog/blob/master/LICENSE"
description = "A minimal theme for non-blog site with a hierarchical sidebar"
homepage = "https://github.com/heavywatal/hugo-theme-nonblog"
demosite = "https://heavywatal.github.io"
tags = ["light", "minimal", "personal", "responsive"]
features = []

[author]
name = "heavywatal"
homepage = "https://heavywatal.github.io"
