name = "nonblog"
license = "MIT"
licenselink = "https://github.com/heavywatal/hugo-theme-nonblog/blob/master/LICENSE"
description = "A minimal theme for non-blog site with a hierarchical sidebar"
tags = ["nonblog", "minimal", "responsive"]
features = ["syntax highlighting"]
min_version = 0.25

[author]
name = "heavywatal"
homepage = "https://heavywatal.github.io"
